spring:
  #  数据库配置
  datasource:
    url:  jdbc:mysql://localhost:3306/datatest?characterEncoding=utf8&serverTimezone=UTC
    username: coolway
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
#mybatis
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl